### ISSUE TITLE
[DOCS] 9204

### ISSUE THREAD

**Issue by ruokeqx** [AutumnQuicHe/RFC9204_Chinese_Simplified#1]
这还翻译吗 空目录不太不知道怎么操作

今天简略地看了一下9204 我的博客里写了第二章第三章一点点东西(有手翻的有机翻的) 有需要的话随意取用

https://ruokeqx.gitee.io/posts/quichttp3_related_rfc/#rfc9204

**Comment by fangqiuhang** [comment]
我今天搭个框架吧

**Comment by YunzheZJU** [comment]
我会按9221-9114-9204-9250的顺序翻译，预期今年年内完成。
遇到看不懂的会去您的博客参考

**Comment by fangqiuhang** [comment]
9204 1、2章终于翻译完了，大伙再帮忙看看吧。
